services:
  pycompressweb:
    # image: anderskeis/pycompressweb:latest
    build: .  # Uncomment to build locally instead of using Docker Hub image
    ports:
      - "5050:5050"
    volumes:
      - pycompressweb-data:/tmp/pycompressweb
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  pycompressweb-data:
